name: dinov3
variant: vits16
path: facebook/dinov3-vits16-pretrain-lvd1689m
patch_size: 16
image_size: 224
use_patch_weights: 1
unfreeze_layers: [0, 1, 2, 3, 4, 5]
unfreeze_norm: 1
freeze_backbone: 1
unfreeze_patch_embed: 1
unfreeze_all_norms: 0
lora:
  layers: null